### ISSUE TITLE
Can't not compile with gcc6.3

### ISSUE THREAD

**Issue by QingGo** [Siile/CSTT#2]
When I compile this code with gcc6.3 and bam, It will show a lot of errors like:
`
src/game/collision.h:69:73: error: call of overloaded ‘round(float&)’ is ambiguous
  int GetCollisionAt(float x, float y) { return GetTile(round(x), round(y)); }
src/base/math.h:23:18: error: ‘int round(float)’ conflicts with a previous declaration
 int round(float f)
`
At the end I delete the function int round(float) in src/base/math.h and every thing is going well.
